//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonsterHunterStories2.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MonsterHunterStories2.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Monster Hunter Stories 2 的本地化字符串。
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Money 的本地化字符串。
        /// </summary>
        public static string MainBasicMoney {
            get {
                return ResourceManager.GetString("MainBasicMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Body Type 的本地化字符串。
        /// </summary>
        public static string MainCharacterBodyType {
            get {
                return ResourceManager.GetString("MainCharacterBodyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Eyes 的本地化字符串。
        /// </summary>
        public static string MainCharacterEyes {
            get {
                return ResourceManager.GetString("MainCharacterEyes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Face Shape 的本地化字符串。
        /// </summary>
        public static string MainCharacterFaceShape {
            get {
                return ResourceManager.GetString("MainCharacterFaceShape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hairstyle 的本地化字符串。
        /// </summary>
        public static string MainCharacterHairStyle {
            get {
                return ResourceManager.GetString("MainCharacterHairStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Makeup 的本地化字符串。
        /// </summary>
        public static string MainCharacterMakeup {
            get {
                return ResourceManager.GetString("MainCharacterMakeup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mouth 的本地化字符串。
        /// </summary>
        public static string MainCharacterMouth {
            get {
                return ResourceManager.GetString("MainCharacterMouth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        public static string MainCharacterName {
            get {
                return ResourceManager.GetString("MainCharacterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Skin 的本地化字符串。
        /// </summary>
        public static string MainCharacterSkin {
            get {
                return ResourceManager.GetString("MainCharacterSkin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Voice 的本地化字符串。
        /// </summary>
        public static string MainCharacterVoice {
            get {
                return ResourceManager.GetString("MainCharacterVoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Smell 的本地化字符串。
        /// </summary>
        public static string MainEggSmell {
            get {
                return ResourceManager.GetString("MainEggSmell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Amazing 的本地化字符串。
        /// </summary>
        public static string MainEggSmellTypeAmazing {
            get {
                return ResourceManager.GetString("MainEggSmellTypeAmazing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Good 的本地化字符串。
        /// </summary>
        public static string MainEggSmellTypeGood {
            get {
                return ResourceManager.GetString("MainEggSmellTypeGood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Normal 的本地化字符串。
        /// </summary>
        public static string MainEggSmellTypeNormal {
            get {
                return ResourceManager.GetString("MainEggSmellTypeNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gene 的本地化字符串。
        /// </summary>
        public static string MainEggTabGene {
            get {
                return ResourceManager.GetString("MainEggTabGene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Armor 的本地化字符串。
        /// </summary>
        public static string MainEquipmentTabArmor {
            get {
                return ResourceManager.GetString("MainEquipmentTabArmor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Talisman 的本地化字符串。
        /// </summary>
        public static string MainEquipmentTabTalisman {
            get {
                return ResourceManager.GetString("MainEquipmentTabTalisman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Weapon 的本地化字符串。
        /// </summary>
        public static string MainEquipmentTabWeapon {
            get {
                return ResourceManager.GetString("MainEquipmentTabWeapon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bow 的本地化字符串。
        /// </summary>
        public static string MainEquipmentWeaponB {
            get {
                return ResourceManager.GetString("MainEquipmentWeaponB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gunlance 的本地化字符串。
        /// </summary>
        public static string MainEquipmentWeaponG {
            get {
                return ResourceManager.GetString("MainEquipmentWeaponG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Great Sword 的本地化字符串。
        /// </summary>
        public static string MainEquipmentWeaponGS {
            get {
                return ResourceManager.GetString("MainEquipmentWeaponGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hammer 的本地化字符串。
        /// </summary>
        public static string MainEquipmentWeaponH {
            get {
                return ResourceManager.GetString("MainEquipmentWeaponH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hunting Horn 的本地化字符串。
        /// </summary>
        public static string MainEquipmentWeaponHH {
            get {
                return ResourceManager.GetString("MainEquipmentWeaponHH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sword &amp; Shield 的本地化字符串。
        /// </summary>
        public static string MainEquipmentWeaponSS {
            get {
                return ResourceManager.GetString("MainEquipmentWeaponSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _About 的本地化字符串。
        /// </summary>
        public static string MainMenuAbout {
            get {
                return ResourceManager.GetString("MainMenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _File 的本地化字符串。
        /// </summary>
        public static string MainMenuFile {
            get {
                return ResourceManager.GetString("MainMenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Exit 的本地化字符串。
        /// </summary>
        public static string MainMenuFileExit {
            get {
                return ResourceManager.GetString("MainMenuFileExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Open... 的本地化字符串。
        /// </summary>
        public static string MainMenuFileOpen {
            get {
                return ResourceManager.GetString("MainMenuFileOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 _Save 的本地化字符串。
        /// </summary>
        public static string MainMenuFileSave {
            get {
                return ResourceManager.GetString("MainMenuFileSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save _As... 的本地化字符串。
        /// </summary>
        public static string MainMenuFileSaveAs {
            get {
                return ResourceManager.GetString("MainMenuFileSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        public static string MainMonsterName {
            get {
                return ResourceManager.GetString("MainMonsterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RideAction 的本地化字符串。
        /// </summary>
        public static string MainMonsterRideAction {
            get {
                return ResourceManager.GetString("MainMonsterRideAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gene 的本地化字符串。
        /// </summary>
        public static string MainMonsterTabGene {
            get {
                return ResourceManager.GetString("MainMonsterTabGene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type 的本地化字符串。
        /// </summary>
        public static string MainMonsterType {
            get {
                return ResourceManager.GetString("MainMonsterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Basic 的本地化字符串。
        /// </summary>
        public static string MainTabBasic {
            get {
                return ResourceManager.GetString("MainTabBasic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Character 的本地化字符串。
        /// </summary>
        public static string MainTabCharacter {
            get {
                return ResourceManager.GetString("MainTabCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Egg 的本地化字符串。
        /// </summary>
        public static string MainTabEgg {
            get {
                return ResourceManager.GetString("MainTabEgg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Equipment 的本地化字符串。
        /// </summary>
        public static string MainTabEquipment {
            get {
                return ResourceManager.GetString("MainTabEquipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Item 的本地化字符串。
        /// </summary>
        public static string MainTabItem {
            get {
                return ResourceManager.GetString("MainTabItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Monster 的本地化字符串。
        /// </summary>
        public static string MainTabMonster {
            get {
                return ResourceManager.GetString("MainTabMonster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bow 的本地化字符串。
        /// </summary>
        public static string MainWeaponB {
            get {
                return ResourceManager.GetString("MainWeaponB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gunlance 的本地化字符串。
        /// </summary>
        public static string MainWeaponG {
            get {
                return ResourceManager.GetString("MainWeaponG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Great Sword 的本地化字符串。
        /// </summary>
        public static string MainWeaponGS {
            get {
                return ResourceManager.GetString("MainWeaponGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hammer 的本地化字符串。
        /// </summary>
        public static string MainWeaponH {
            get {
                return ResourceManager.GetString("MainWeaponH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hunting Horn 的本地化字符串。
        /// </summary>
        public static string MainWeaponHH {
            get {
                return ResourceManager.GetString("MainWeaponHH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sword &amp;amp; Shield 的本地化字符串。
        /// </summary>
        public static string MainWeaponSS {
            get {
                return ResourceManager.GetString("MainWeaponSS", resourceCulture);
            }
        }
    }
}
