//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonsterHunterStories2.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MonsterHunterStories2.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Monster Hunter Stories 2 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Money に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainBasicMoney {
            get {
                return ResourceManager.GetString("MainBasicMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Body Type に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainCharacterBodyType {
            get {
                return ResourceManager.GetString("MainCharacterBodyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Eyes に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainCharacterEyes {
            get {
                return ResourceManager.GetString("MainCharacterEyes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Face Shape に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainCharacterFaceShape {
            get {
                return ResourceManager.GetString("MainCharacterFaceShape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hairstyle に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainCharacterHairStyle {
            get {
                return ResourceManager.GetString("MainCharacterHairStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Makeup に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainCharacterMakeup {
            get {
                return ResourceManager.GetString("MainCharacterMakeup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mouth に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainCharacterMouth {
            get {
                return ResourceManager.GetString("MainCharacterMouth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainCharacterName {
            get {
                return ResourceManager.GetString("MainCharacterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Skin に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainCharacterSkin {
            get {
                return ResourceManager.GetString("MainCharacterSkin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Voice に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainCharacterVoice {
            get {
                return ResourceManager.GetString("MainCharacterVoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Smell に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainEggSmell {
            get {
                return ResourceManager.GetString("MainEggSmell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Amazing に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainEggSmellTypeAmazing {
            get {
                return ResourceManager.GetString("MainEggSmellTypeAmazing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Good に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainEggSmellTypeGood {
            get {
                return ResourceManager.GetString("MainEggSmellTypeGood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Normal に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainEggSmellTypeNormal {
            get {
                return ResourceManager.GetString("MainEggSmellTypeNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gene に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainEggTabGene {
            get {
                return ResourceManager.GetString("MainEggTabGene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Armor に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainEquipmentTabArmor {
            get {
                return ResourceManager.GetString("MainEquipmentTabArmor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Weapon に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainEquipmentTabWeapon {
            get {
                return ResourceManager.GetString("MainEquipmentTabWeapon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bow に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainEquipmentWeaponB {
            get {
                return ResourceManager.GetString("MainEquipmentWeaponB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gunlance に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainEquipmentWeaponG {
            get {
                return ResourceManager.GetString("MainEquipmentWeaponG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Great Sword に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainEquipmentWeaponGS {
            get {
                return ResourceManager.GetString("MainEquipmentWeaponGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hammer に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainEquipmentWeaponH {
            get {
                return ResourceManager.GetString("MainEquipmentWeaponH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hunting Horn に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainEquipmentWeaponHH {
            get {
                return ResourceManager.GetString("MainEquipmentWeaponHH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sword &amp; Shield に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainEquipmentWeaponSS {
            get {
                return ResourceManager.GetString("MainEquipmentWeaponSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _About に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainMenuAbout {
            get {
                return ResourceManager.GetString("MainMenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainMenuFile {
            get {
                return ResourceManager.GetString("MainMenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Exit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainMenuFileExit {
            get {
                return ResourceManager.GetString("MainMenuFileExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Open... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainMenuFileOpen {
            get {
                return ResourceManager.GetString("MainMenuFileOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _Save に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainMenuFileSave {
            get {
                return ResourceManager.GetString("MainMenuFileSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save _As... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainMenuFileSaveAs {
            get {
                return ResourceManager.GetString("MainMenuFileSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainMonsterName {
            get {
                return ResourceManager.GetString("MainMonsterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   RideAction に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainMonsterRideAction {
            get {
                return ResourceManager.GetString("MainMonsterRideAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gene に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainMonsterTabGene {
            get {
                return ResourceManager.GetString("MainMonsterTabGene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Type に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainMonsterType {
            get {
                return ResourceManager.GetString("MainMonsterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Basic に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainTabBasic {
            get {
                return ResourceManager.GetString("MainTabBasic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Character に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainTabCharacter {
            get {
                return ResourceManager.GetString("MainTabCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Egg に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainTabEgg {
            get {
                return ResourceManager.GetString("MainTabEgg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Equipment に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainTabEquipment {
            get {
                return ResourceManager.GetString("MainTabEquipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Item に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainTabItem {
            get {
                return ResourceManager.GetString("MainTabItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Monster に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MainTabMonster {
            get {
                return ResourceManager.GetString("MainTabMonster", resourceCulture);
            }
        }
    }
}
